### ISSUE TITLE
Fails with `no writecb in Transform class`

### ISSUE THREAD

**Issue by porglezomp** [purescript-contrib/gulp-purescript#41]
When I attempt to use gulp-purescript in any way, I get
`Error: no writecb in Transform class`
Setting up a directory that contains
```
Gulpfile.js
node_modules
package.json
src/
        test.purs
```
Where `Gulpfile.js` is the example Gulpfile that's provided.

The full error is:
```
Error: no writecb in Transform class
    at afterTransform (/Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
    at TransformState.afterTransform (/Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/index.js:7907:14
    at /Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/index.js:7508:21
    at /Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/index.js:7518:12
    at /Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/index.js:7441:22
    at /Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/index.js:7501:17
    at DestroyableTransform.transform [as _transform] (/Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/index.js:7921:17)
    at DestroyableTransform.Transform._read (/Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/caleb/Development/gulp-minimal/node_modules/gulp-purescript/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
```

**Comment by porglezomp** [comment]
Oops, I see that #37 is this same issue. I'll close this one.
